language: python
python:
  - '3.6'
script:
  - make test
  - python setup.py sdist

# https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  on:
    tags: true
  user: jfly
  password:
    secure: bvW8g8swjWyf1XpunKLoSZJUSC2VcfPaEbXQnO8jAh3kBvAFsnTyr2sy/kTE7NkA0qQXyQ5FzGONEzFDsGdn+TvjfCF53VMR3+0SVg2EBzN42aydv7ENyVrTOgsKhzbtQX4TkO0QpQhniqzA6XDMrU671vvuM31tXLm2fn74bio8kBwM/dqLB4PqcHcrB2dFCrKxPvSIFWqig+k6QJzN/RfAxtiHpiSbaQTy8kJ8TNrtLc0ybGsir0hYeeowk+ifxrOPO+HLEzleoh0onQ4bb1H1rzmHxxgfj67gPbnmCu92Upy9AjK1coIy0Gd8X/Vw3zBUjMgYrWdpjQkiBXIJDlckYI3hb7aUH1JH318izU3I875GiQVBIC97CDmSp/SntEII6LOwhuDRhW1IdANX6YLO5fn5wscEftsYQlRWR8Vzeoq9c5xapq0Jy49lqeaGZxeYAqa1NtmPZC1GKw3OfadQIrE8OfBxx6BCL/e0ZmOlO9hpak4mB5ukkPvBtmtPP46VjyQDnFFgMAlW5nAsSZJW1RYVTwNdQBvoS0+Axfnpfqmf/ODUTeUMDtvRg9HlDKFHG1lT7ZOcttIcJUsTViJatVUL3/ZGABQic0pxWtBGlZwWMUkrc9esREH6zbaqfV+rRRSngFESw7OHfGjmFxgPqC6M30yKullvs3pITRY=
